module.exports = {
  user: {
    firstName: 'Amy',
    lastName: 'Awesome',
    email: 'amy@testemail.com',
    hash: '$2a$10$flgD5OmkK2cwd/7CddCOW.Ujd30tqTb4r02bYVfYuI/GlwKw5gNt.',
    gender: 'Female',
    zip: '94519',
    workZip: '94108',
    birthDate: '1988-07-19',
  },
  closet: {
    name: 'My Closet',
    isPrivate: 'true'
  },
  items: [
    {
      brandName: 'Topshop',
      itemName: 'Cowl Neck Camisole',
      size: '4',
      sku: 5557142,
      s3PublicUrl: 'https://n.nordstrommedia.com/ImageGallery/store/product/Zoom/12/_102747532.jpg?crop=pad&pad_color=FFF&format=jpeg&w=60&h=90',
      price: '24',
      lastWornDate: '2018-07-19',
      isFavorite: true,
      timesWorn: 10,
      maxTimesBeforeWash: 1,
      isClean: true,
      color: 'Black',
      closet: 'My Closet',
      style: 'Camisole',
      purchaseDate: '2018-02-01'
    },
    {
      brandName: 'BP',
      itemName: 'Raw Edge V-Neck Tee',
      size: '4',
      sku: 5370727,
      s3PublicUrl: 'https://n.nordstrommedia.com/ImageGallery/store/product/Zoom/13/_101151053.jpg?crop=pad&pad_color=FFF&format=jpeg&w=60&h=90',
      price: '17',
      lastWornDate: '2018-07-19',
      isFavorite: true,
      timesWorn: 30,
      maxTimesBeforeWash: 1,
      isClean: true,
      color: 'Orange',
      closet: 'My Closet',
      style: 'T-Shirt/Tank',
      purchaseDate: '2018-03-01'
    },
    {
      brandName: 'Spanx',
      itemName: 'Camo Faux Leather Leggings',
      size: 'Medium',
      sku: 798736,
      s3PublicUrl: 'https://n.nordstrommedia.com/ImageGallery/store/product/Zoom/11/_101901771.jpg?crop=pad&pad_color=FFF&format=jpeg&w=60&h=90',
      price: '98',
      lastWornDate: '2018-08-08',
      isFavorite: true,
      timesWorn: 2,
      maxTimesBeforeWash: 2,
      isClean: true,
      color: 'Blue',
      closet: 'My Closet',
      style: 'Legging',
      purchaseDate: '2018-08-01'
    },
    {
      brandName: 'Topshop',
      itemName: 'Popper Utility Trousers',
      size: 'Medium',
      sku: 5653449,
      s3PublicUrl: 'https://n.nordstrommedia.com/ImageGallery/store/product/Zoom/9/_103541349.jpg?crop=pad&pad_color=FFF&format=jpeg&w=60&h=90',
      price: '75',
      lastWornDate: '2018-08-04',
      isFavorite: true,
      timesWorn: 3,
      maxTimesBeforeWash: 2,
      isClean: true,
      color: 'Blue',
      closet: 'My Closet',
      style: 'Trouser',
      purchaseDate: '2018-05-01'
    },
    {
      brandName: 'Caslon',
      itemName: 'Utility Jacket',
      size: 'Medium',
      sku: 5560277,
      s3PublicUrl: 'https://n.nordstrommedia.com/ImageGallery/store/product/Zoom/17/_103021737.jpg?crop=pad&pad_color=FFF&format=jpeg&w=60&h=90',
      price: '79',
      lastWornDate: '2018-07-04',
      isFavorite: true,
      timesWorn: 2,
      maxTimesBeforeWash: 3,
      isClean: true,
      color: 'Green',
      closet: 'My Closet',
      style: 'Denim',
      purchaseDate: '2018-06-01'
    },
    {
      brandName: 'Caslon',
      itemName: 'Two Pocket Knit Blazer',
      size: 'Medium',
      sku: 5560281,
      s3PublicUrl: 'https://n.nordstrommedia.com/ImageGallery/store/product/Zoom/17/_103021737.jpg?crop=pad&pad_color=FFF&format=jpeg&w=60&h=90',
      price: '59',
      lastWornDate: '2018-08-02',
      isFavorite: true,
      timesWorn: 1,
      maxTimesBeforeWash: 3,
      isClean: true,
      color: 'Gray',
      closet: 'My Closet',
      style: 'Trench',
      purchaseDate: '2018-02-01'
    }
  ]
};
