//for code meanings see https://developer.yahoo.com/weather/documentation.html#codes
const weatherOptions = {
  0: 'tornado',
  1: 'hurricane',
  2: 'hurricane',
  3: 'storm',
  4: 'storm',
  5: 'snow',
  6: 'snow',
  7: 'snow',
  8: 'sprinkles',
  9: 'sprinkles',
  10: 'showers',
  11: 'showers',
  12: 'showers',
  13: 'snow',
  14: 'snow',
  15: 'snow',
  16: 'snow',
  17: 'hail',
  18: 'snow',
  19: 'cloudy',
  20: 'cloudy',
  21: 'cloudy',
  22: 'cloudy',
  23: 'windy',
  24: 'windy',
  25: 'cloudy',
  26: 'cloudy',
  27: 'partly_cloudy',
  28: 'partly_cloudy',
  29: 'partly_cloudy',
  30: 'partly_cloudy',
  31: 'sunny',
  32: 'sunny',
  33: 'sunny',
  34: 'sunny',
  35: 'hail',
  36: 'sunny',
  37: 'storm',
  38: 'storm',
  39: 'storm',
  40: 'showers',
  41: 'snow',
  42: 'snow',
  43: 'snow',
  44: 'partly_cloudy',
  45: 'storm',
  46: 'snow',
  47: 'snow',
  default: 'sunny'
}

export default weatherOptions;